server:
  port: 8080
  
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:
    hostname: localhost
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: service-user
          uri: lb://service-user
          predicates:
            - Path=/api/users/**
          filters:
            - name: AuthFilter
              args:
                publicMethods: 'GET'
                paths: 
                  - '/api/users/new-user'
        - id: service-blog
          uri: lb://service-blog
          predicates:
            - Path=/api/blogs/**
        - id: service-comments
          uri: lb://service-comments
          predicates:
            - Path=/api/comments/**
        - id: service-auth
          uri: lb://service-auth
          predicates:
            - Path=/auth/**
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      probability: 1.0